- name: Clone frontend repository
  git:
    repo: "https://github.com/keilevv/autoexpress-client.git"
    dest: "/var/www/frontend"
    force: yes

- name: Copy .env file
  template:
    src: .env.j2
    dest: /var/www/frontend/.env

- name: Ensure Vite is installed globally (optional)
  npm:
    name: vite
    global: yes

- name: Install frontend dependencies
  command: npm install
  args:
    chdir: /var/www/frontend

- name: Build frontend app
  command: npm run build
  args:
    chdir: /var/www/frontend

- name: Move frontend build to Nginx root
  command: mv /var/www/frontend/dist /var/www/frontend_build

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
