#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx
  - nodejs
  - npm
  - git

runcmd:
  - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  - apt-get install -y nodejs
  - npm install -g pm2
  - git clone https://github.com/keilevv/autoexpress-client.git /var/www/autoexpress-client
  - cd /var/www/autoexpress-client && npm install && npm run build
  - rm /etc/nginx/sites-enabled/default
  - echo '
    server {
        listen 80;
        server_name _;
        root /var/www/autoexpress-client/dist;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api {
            proxy_pass http://${loadbalancer_ip}:80;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }' > /etc/nginx/sites-available/autoexpress
  - ln -s /etc/nginx/sites-available/autoexpress /etc/nginx/sites-enabled/
  - systemctl restart nginx
  - systemctl enable nginx
