- name: Clone backend repository
  git:
    repo: "https://github.com/keilevv/autoexpress-server.git"
    dest: "/var/www/backend"
    force: yes

- name: Copy .env file
  template:
    src: .env.j2
    dest: /var/www/backend/.env

- name: Install backend dependencies
  command: npm install
  args:
    chdir: /var/www/backend

- name: Start backend server with PM2
  command: pm2 start npm --name "backend" -- run start
  args:
    chdir: /var/www/backend

- name: Save PM2 process list
  command: pm2 save
